### PR TITLE
fixed profile showing information

### LINKED ISSUE #11: Enhance Profile feature
- Add profile verification for students (using university email)
- Include vehicle information for drivers
- Add profile pictures (avatar)

### PR DESCRIPTION
**Pull request by Haytham-Ziani**

### CODE REVIEW

**Comment by aliceduongg** [comment]
I am testing on it, will notify if it passed all cases

File: frontend/app/components/profile.tsx
Comment (aliceduongg) [inline frontend/app/components/profile.tsx:1]: Info will be parsed  to the profile:  firstName, lastName, phoneNumber and email (can't change)

File: frontend/app/components/profile.tsx [hunk 1]
```diff
@@ -14,16 +14,19 @@ export function Profile() {
...
   useEffect(() => {
     const storedUser = localStorage.getItem('user');
     if (storedUser) {
       const parsedUser = JSON.parse(storedUser);
       console.log('Retrieved user from local storage:', parsedUser); // Debug log to check user data
       setUser(parsedUser);
-      if (parsedUser.id) {
-        fetchUserProfile(parsedUser.id);
-      }
+    // Set firstName and lastName from the retrieved user
```
Comment (aliceduongg) [inline frontend/app/components/profile.tsx:25]: Will works with new users, and previous users will be impacted by these changes

**Review by aliceduongg — CHANGES_REQUESTED** [review]
Some fields will be parsed to the profile (if they are new users). However if I logout and login again, the info in update profile again fail to handle fetching info -> UI not display user information.
